version: "3.9"
services:
  bq:
    image: ghcr.io/goccy/bigquery-emulator:latest
    container_name: bq-emulator
    ports:
      - 9050:9050
    working_dir: /work
    volumes:
      - ./db:/work/db
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
    command: --project=${DEFAULT_PROJECT_ID} --data-from-yaml=${DEFAULT_SEED_OUTPUT}
  gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: gcs-emulator
    ports:
      - 4443:4443
    volumes:
      - ./gcs-data:/data
    command: -scheme http -public-host ${URL:-localhost}:4443
